### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by caiyongqi** [gaoxiangjun/MPS-NeRF#1]
Could you describe how the data (images, camera parameters and so on) used in this paper  are made from the Thuman1.0 dataset? I am planning to render images from Thuman2.0.

**Comment by gaoxiangjun** [comment]
Hi yongqi, for each person and each pose, we render 24 images from different camera viewpoints. All the cameras point to body center with their azimuth and elevation angles evenly-sampled in [0◦,360◦] and [0◦,35◦], respectively. The reconstructed SMPL parameters provided by the THuman dataset are used.
