### ISSUE TITLE
The code and command for processing the ZJU-MoCap dataset

### ISSUE THREAD

**Issue by jingfengguo-ai** [gaoxiangjun/MPS-NeRF#10]
Thank you very much for your great work MPS-NeRF. I noticed the experimental results on the ZJU-MoCap Dataset mentioned in section 4.4 of your paper. I sincerely hope you can provide the code and command for processing the ZJU-MoCap dataset. If you provide relevant code, I promise to reference your paper in our future work！

**Comment by gaoxiangjun** [comment]
https://github.com/gaoxiangjun/MPS-NeRF/issues/2#issuecomment-1473264460
 hope this helps you.

**Comment by jingfengguo-ai** [comment]
> [#2 (comment)](https://github.com/gaoxiangjun/MPS-NeRF/issues/2#issuecomment-1473264460) hope this helps you.



> [#2 (comment)](https://github.com/gaoxiangjun/MPS-NeRF/issues/2#issuecomment-1473264460) hope this helps you.


Thank you for your response. I have encountered another issue. I have requested the link to the Human3.6M dataset from the animatable_nerf repository, but it does not contain files such as '45_big_pose_tvertices.npy.'

**Comment by gaoxiangjun** [comment]
> > [#2 (comment)](https://github.com/gaoxiangjun/MPS-NeRF/issues/2#issuecomment-1473264460) hope this helps you.
> 
> > [#2 (comment)](https://github.com/gaoxiangjun/MPS-NeRF/issues/2#issuecomment-1473264460) hope this helps you.
> 
> Thank you for your response. I have encountered another issue. I have requested the link to the Human3.6M dataset from the animatable_nerf repository, but it does not contain files such as '45_big_pose_tvertices.npy.'

https://github.com/gaoxiangjun/MPS-NeRF/issues/3#issuecomment-1434561814 Please check here.
