### ISSUE TITLE
ZJU-MoCap dataset

### ISSUE THREAD

**Issue by GostInShell** [gaoxiangjun/MPS-NeRF#2]
Hi! Thanks for contributing you code!

I am planning to reproduce your method on ZJU-Mocap. Would you please share the dataset code, and training scripts please. 
Thanks!

**Comment by gaoxiangjun** [comment]
[neubody_dataset.py.zip](https://github.com/gaoxiangjun/MPS-NeRF/files/10998578/neubody_dataset.py.zip)
Here is the dataloader for the ZJU-MoCap dataset. Please check it. You may need to adapt the code to meet your own requirements.
