### ISSUE TITLE
 No such file or directory: 'data/h36m/S9/Posing/45_big_pose_tvertices.npy' 

### ISSUE THREAD

**Issue by pansanity666** [gaoxiangjun/MPS-NeRF#3]
Hi, 
   I used the processes h36m from animatable NeRF authors, however, I got this error.  
   Did you process h36m yourself additionally?
Best,

**Comment by gaoxiangjun** [comment]
Hi, the pre-processed H36M canonical pose vertices are attached as follows.
[45_big_pose_vertices.zip](https://github.com/gaoxiangjun/MPS-NeRF/files/10766560/45_big_pose_vertices.zip)
