### ISSUE TITLE
Can you provide the used mesh in Thuman 1.0 ?

### ISSUE THREAD

**Issue by pansanity666** [gaoxiangjun/MPS-NeRF#6]
Hi, 
     I am wondering the GT mesh from Thuman 1.0 for 3D mesh comparison. Could you provide the selected meshes in your preprocessed dataset? Thanks!
Best,

**Comment by gaoxiangjun** [comment]
You can find the selected person here.
data/THuman_1_human_list.txt

**Comment by pansanity666** [comment]
> You can find the selected person here. data/THuman_1_human_list.txt

Thanks，I will try it. 
By the way,  have you ever tried to report 3D metrics like Chamfer Distance in Thuman1.0?  
I find that most works do not compare 3D meshes for Thuman 1.0 though the GT meshes are available.

Best,

**Comment by gaoxiangjun** [comment]
Sure. Our goal is human rendering, so I didn't evaluate the mesh accuracy in my experiments.

Best,
