### ISSUE TITLE
Query on H36m Processed File

### ISSUE THREAD

**Issue by Dipankar1997161** [gaoxiangjun/MPS-NeRF#7]
Thank you for the work.

Actually I would like to know, how can I generate the processed file for human3.6m dataset. 
I saw the processed file by animatable nerf, however, they only provide "Posing", I would like to generate SMPL (vertices and params for other actions atleast 2 of them) 

Can you provide any information on this?

**Comment by gaoxiangjun** [comment]
The processed file for human3.6m dataset is provided by animatable nerf paper, you may ask their author for details.

**Comment by Dipankar1997161** [comment]
Ok thank you
