### ISSUE TITLE
How to generate human3.6M training data from the original Human3.6M dataset?

### ISSUE THREAD

**Issue by TonNew5418** [gaoxiangjun/MPS-NeRF#8]
I've already setup the environment, but while running the training command for h36m s1 dataset, the error “FileNotFoundError: [Errno 2] No such file or directory: './data/h36m/S1/Posing/annots.npy'" occurs. 

I want to know how to generate the npy file since it is not contained in the original h36m dataset and possibly the dataset structure to train the model.

**Comment by TonNew5418** [comment]
Also, the paper says the input needs to include SMPL model shape and pose parameters fitted to the input images. I want to know how to generate these parameters from human3.6m dataset.

**Comment by Dipankar1997161** [comment]
@TonNew5418,
The file you are looking for is provided by "Animetable NERF" you can directly ask them for the processed file. It has the files you are looking for

**Comment by gaoxiangjun** [comment]
> @TonNew5418, The file you are looking for is provided by "Animetable NERF" you can directly ask them for the processed file. It has the files you are looking for

@Dipankar1997161 Thanks for your reply. @TonNew5418 may check this.
